version: "3"
services:
  redis:
    container_name: redis
    image: redis

  backend:
    container_name: backend
    environment:
      - PORT=4000
      - MONGODB_CONNECTION=mongodb://mongo:27017/Ademola
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./backend:/app
    command: npm run dev

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:80"

  mongo:
    container_name: mongo
    image: mongo
# the client part
  frontend:
    container_name: frontend
    build:
      context: ./front_end
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./front_end:/app

      # the worker
  worker:
    container_name: worker
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=5000
      - REDIS_CONNECTION=redis://redis
